spring:
application:
name: quizapp
datasource:
url: jdbc:h2:mem:quizdb
driver-class-name: org.h2.Driver
h2:
console:
enabled: true
jpa:
hibernate:
ddl-auto: create-drop
show-sql: true


thymeleaf:
cache: false

server:
port: ${PORT:8080}